### ISSUE TITLE
Question: is it possible to open file in $EDITOR at the current cursor line?

### ISSUE THREAD

**Issue by alok** [inducer/pudb#211]
I often find a bug and then have to open up an editor to, well, *edit* it. It'd be nice if I could just hit a key.

**Comment by cdman** [comment]
Hmm, a quick search seems to indicate that both `vim` (`vi`?) and `nano` support the `$EDITOR +$LINE_NUMBER $FILE_NAME` syntax, so this could be made to work for at least a large amount of cases. However I worry that it might be confusing since Python doesn't provide auto-reload out of the box... (so you debug your file, edit it, close the editor and then you're back at the unchanged file in the debugger?).

**Comment by asmeurer** [comment]
After editing it could pop up a dialog asking to continue with the pre-edited version or to quit. Maybe also restart with `reload` with the caveat that `reload` can sometimes introduce its own bugs.

**Comment by huangyuyao** [comment]
Any update?

**Comment by asmeurer** [comment]
No one is working on it as far as I know. It shouldn't be too hard to implement.

**Comment by gaborvecsei** [comment]
I'd also love this feature!

**Comment by gaborvecsei** [comment]
I created a pull request which solves this issue: #430

**Comment by gaborvecsei** [comment]
My PR is merged. From now on, you can enjoy file editing 😊 Just hit `Ctrl-e`. 😉 

(I think this issue can be closed)

**Comment by bostone** [comment]
This doesn't work if `nano` editor is missing which is my case (I'm in Docker container with only vi available)

**Comment by asmeurer** [comment]
You should be able to fix it by setting `EDITOR=vi` in the docker environment. `nano` is used as a default if `EDITOR` is not set.

**Comment by inducer** [comment]
Closing as per discussion above, cf. #430.
