### ISSUE TITLE
Provide a simple way to install pudb's tab-completion

### ISSUE THREAD

**Issue by rbarrois** [inducer/pudb#414]
Before #350, tab completion was provided natively through Python's readline module.
New versions rely on a third party dependency, which adds an extra step to setup ­— and requires user to install an extra package without a relation with pudb.

It would be great if users could directly install pudb and its tab-completion support in a single `pip install`:
- Either add a fallback on Python's `readline` module if `jedi` can't be found;
- Or add an optional extra that pulls in a compatible version of `jedi`, e.g `pip install pudb[completion]`

If one of those options interests you, I'll be glad to provide a pull-request accordingly ;)

And thanks again for pudb, it's an amazing program 😉

**Comment by inducer** [comment]
The optional extra sounds good to me. But I'm also open to making jedi a hard dependency. What do you think? @asmeurer any thoughts?

**Comment by rbarrois** [comment]
Just a quick note: on my setup, the first tab completion (with jedi) seems to take at least half a second, whereas it was nearly instant with readline :/

**Comment by inducer** [comment]
If you'd like `rlcompleter` back as a fallback, I'm open to looking at a PR.

**Comment by asmeurer** [comment]
The only issue is that rlcompleter causes issues on the system Python on macOS (see the issues corresponding to that PR). Simply importing it imports `readline`, which seems to cause issues. A solution could be to extract the dircompleter stuff from the rlcompleter module so that we can use it without importing readline. Or figure out why libedit breaks urwid and fix the bug (but good luck with that). I also wonder if Jedi has a faster dir() only completer option.

**Comment by inducer** [comment]
@asmeurer Ah, thanks for for reminding me. In that case, no, we probably shouldn't bring `rlcompleter` back.
